name: CI (Unit tests)
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Set env variables
      run: 
        export JEST_SOLANA_NETWORK=mainnet-beta
    - name: Run unit-tests (Jest)
      run: yarn test